[MINGW] fix compile error b/c fixed keyword BOOL for Windows
gcc -c -D__USE_MINGW_ANSI_STDIO -DHAVE_LIBREADLINE -DHAVE_MPFR -O2 -gdwarf-2 -g3 -Wno-deprecated-declarations -DGAWK -I. -I./support -DHAVE_CONFIG_H -DDEFPATH="\".;c:/gnu/lib/awk;c:/lib/awk;c:/gnu/lib/awk\"" -DDEFLIBPATH="\"c:/gnu/lib/gawk\"" -DSHLIBEXT="\"dll\"" -DLOCALEDIR="\"c:/gnu/share/locale\"" gawkmisc.c
In file included from D:/a/_temp/msys64/mingw32/include/windef.h:9,
                 from D:/a/_temp/msys64/mingw32/include/windows.h:69,
                 from D:/a/_temp/msys64/mingw32/include/winsock2.h:23,
                 from ./socket.h:34,
                 from pc/gawkmisc.pc:46,
                 from gawkmisc.c:36:
D:/a/_temp/msys64/mingw32/include/minwindef.h:131:15: error: 'BOOL' redeclared as different kind of symbol
  131 |   typedef int BOOL;
      |               ^~~~
In file included from gawkmisc.c:27:
awk.h:452:17: note: previous definition of 'BOOL' with type 'enum flagvals'
  452 |                 BOOL    = 0x0040,       /* this is a boolean value */
      |                 ^~~~

The BOOL keyword chosen by GAWK in awk.h (cf. commit 200c22e) interferes
with the Windows keyword BOOL.  Use - for Windows - WINBOOL instead.

* pc/popen.c: replace BOOL by WINBOOL.